// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `json:"name"`
}

type Response struct {
	Message string   `json:"message"`
	Name    Response `json:"name"`
	Age     int64    `json:"age"`
}
